# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT
### Installing depedencies...
### set http_proxy=http://10.144.1.10:8080; set https_proxy=https://10.144.1.10:8080

# config InfluxDB repo
sudo /vagrant_data/add_yum_repo.sh

sudo yum -y install epel-release
sudo yum -y install python python-pip git wget python-devel openssl-devel gcc gcc-c++ java-1.8.0-openjdk-devel java-1.8.0-openjdk influxdb
sudo pip install --upgrade pip
sudo pip install requests influxdb prettytable xlsxwriter


sudo nmcli connection reload
sudo systemctl restart network.service

sudo systemctl enable influxdb.service
sudo systemctl daemon-reload
sudo cp /vagrant_data/influxdb.conf /etc/influxdb/
sudo systemctl restart influxdb.service




SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.proxy.http  = "http://10.144.1.10:8080"
    config.proxy.https = "http://10.144.1.10:8080"
    config.proxy.no_proxy = "localhost, 127.0.0.1"
		
		config.vm.network :forwarded_port, guest: 8086, host: 4086
		config.vm.network :forwarded_port, guest: 8083, host: 4083
    config.vm.box = "boxcutter/centos73"
    config.vm.synced_folder "E:/code/personal", "/vagrant_data"
    config.vm.provision "shell", inline: $script
    
    config.vm.define "laojiao" do |laojiao|
      laojiao.vm.network "private_network", ip: "192.168.64.18"
      laojiao.vm.hostname = "LaoJiao"
    end         
end
